apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyterhubproxy
  namespace: agwtest
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: proxy-public
            port:
              number: 80
        pathType: Exact